### ISSUE TITLE
[Bug] Task Name hidden by the day strip

### ISSUE THREAD

**Issue by loucass003** [GreaseMonk/android-timetable#3]
Please change your setText call in bindView (GridItem.java) by

```
holder.textView.setText(model != null ? model.getName() : "");
```

For showing the text

**Comment by loucass003** [comment]
Woops. Wrong way delete it

**Comment by GreaseMonk** [comment]
no problem @loucass003 I will close this issue now. If there is anything else just open up a new one or send me a PR
